services:
  arlocal:
    profiles: ['test']
    image: textury/arlocal:v1.1.35
    ports:
      - '1984:1984'

  arns-service:
    build:
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION:-18.16.0}
        NODE_VERSION_SHORT: ${NODE_VERSION_SHORT:-18}
    environment:
      NODE_ENV: ${NODE_ENV:-dev}
      GATEWAY_HOST: ${GATEWAY_HOST:-arlocal}
      GATEWAY_PORT: ${GATEWAY_PORT:-1984}
      GATEWAY_PROTOCOL: ${GATEWAY_PROTOCOL:-http}
      PREFETCH_CONTRACTS: ${PREFETCH_CONTRACTS:-false}
      BLOCKLISTED_CONTRACT_IDS: ${BLOCKLISTED_CONTRACT_IDS:-fbU8Y4NMKKzP4rmAYeYj6tDrVDo9XNbdyq5IZPA31WQ}
      WAIT_TIME_SECONDS: ${WAIT_TIME_SECONDS:-}
    ports:
      - '3000:3000'
    volumes:
      - ${WARP_SQLITE_CACHE_PATH:-./cache/warp/sqlite}:/usr/src/app/cache/sqlite

  litestream:
    profiles: ['litestream']
    build:
      context: litestream
    environment:
      TVAL_LOCAL_DB_PATH: ${LITESTREAM_LOCAL_DB_PATH:-/app/data/sqlite}
      TVAL_S3_BUCKET_PATH: ${LITESTREAM_S3_BUCKET_PATH:-}
      TVAL_S3_BUCKET: ${LITESTREAM_S3_BUCKET:-}
      TVAL_AWS_ACCESS_KEY_ID: ${LITESTREAM_AWS_ACCESS_KEY_ID:-}
      TVAL_AWS_SECRET_ACCESS_KEY: ${LITESTREAM_AWS_SECRET_ACCESS_KEY:-}
      TVAL_S3_BUCKET_REGION: ${LITESTREAM_S3_BUCKET_REGION:-}
      WAIT_TIME_SECONDS: ${LITESTREAM_WAIT_TIME_SECONDS:-}
      RESTORE_FROM_BACKUP: ${LITESTREAM_RESTORE_FROM_BACKUP:-false}
    volumes:
      - ${WARP_SQLITE_CACHE_PATH:-./cache/warp/sqlite}:/app/data/sqlite

  test-runner:
    profiles: ['test']
    build:
      context: .
      dockerfile: tests/integration/Dockerfile.integration
      args:
        NODE_VERSION: ${NODE_VERSION:-18.16.0}
    environment:
      HOST: arns-service
      PORT: 3000
      GATEWAY_HOST: ${GATEWAY_HOST:-arlocal}
      WARP_GATEWAY_HOST: ${GATEWAY_HOST:-arlocal}
      GATEWAY_PORT: ${GATEWAY_PORT:-1984}
      GATEWAY_PROTOCOL: ${GATEWAY_PROTOCOL:-http}
      BLOCKLISTED_CONTRACT_IDS: ${BLOCKLISTED_CONTRACT_IDS:-fbU8Y4NMKKzP4rmAYeYj6tDrVDo9XNbdyq5IZPA31WQ}
    depends_on:
      - arlocal
      - arns-service
