version: '3'

services:
  arlocal:
    image: textury/arlocal:v1.1.35
    ports:
      - '1984:1984'

  arns-service:
    build:
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION:-18.16.0}
        NODE_VERSION_SHORT: ${NODE_VERSION_SHORT:-18}
    environment:
      NODE_ENV: ${NODE_ENV:-dev}
      GATEWAY_HOST: ${GATEWAY_HOST:-arlocal}
      GATEWAY_PORT: ${GATEWAY_PORT:-1984}
      GATEWAY_PROTOCOL: ${GATEWAY_PROTOCOL:-http}
      PREFETCH_CONTRACTS: ${PREFETCH_CONTRACTS:-false}
      BLOCKLISTED_CONTRACT_IDS: ${BLOCKLISTED_CONTRACT_IDS:-fbU8Y4NMKKzP4rmAYeYj6tDrVDo9XNbdyq5IZPA31WQ}
      WAIT_TIME_SECONDS: ${WAIT_TIME_SECONDS:-}
    ports:
      - '3000:3000'

  test-runner:
    build:
      context: .
      dockerfile: tests/integration/Dockerfile.integration
      args:
        NODE_VERSION: ${NODE_VERSION:-18.16.0}
    environment:
      HOST: arns-service
      PORT: 3000
      GATEWAY_HOST: ${GATEWAY_HOST:-arlocal}
      GATEWAY_PORT: ${GATEWAY_PORT:-1984}
      GATEWAY_PROTOCOL: ${GATEWAY_PROTOCOL:-http}
      BLOCKLISTED_CONTRACT_IDS: ${BLOCKLISTED_CONTRACT_IDS:-fbU8Y4NMKKzP4rmAYeYj6tDrVDo9XNbdyq5IZPA31WQ}
    depends_on:
      - arlocal
      - arns-service
